name: clean_artitecture
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  #For Networking
  retrofit: ^4.0.1
  dio: ^5.1.2

  #For Routing
  auto_route: ^7.4.0

  #For Icons
  ionicons: ^0.2.2

  #For comparing the dart objects
  equatable: ^2.0.5

  #For logging the loggers in the terminal
  awesome_dio_interceptor: ^1.0.0

  #For Statemanagment
  flutter_bloc: ^8.1.3
  
  #For database
  floor: ^1.4.2

  #For dependency injection
  get_it: ^7.6.0

  #others
  flutter_hooks: ^0.18.6

  #For Showimg the toast message
  oktoast: ^3.3.1

  
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  lint: ^2.0.20
  json_serializable: ^6.7.0
  floor_generator: ^1.4.2
  retrofit_generator: ^7.0.1

  

flutter:
  uses-material-design: true
